AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SlackProxyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SlackProxyApp
      Handler: lambda.handler
      Runtime: ruby2.5
      CodeUri: "./"
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SLACK_USERNAME:
          SLACK_WEBHOOK_URL:
      Events:
        SlackProxyAPI:
            Type: Api
            Properties:
                Path: /
                Method: ANY
                RestApiId: !Ref SlackProxyAPI
  SlackProxyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: SlackProxyAPI
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        basePath: '/Prod'
        info:
          title: !Ref AWS::StackName
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlackProxyFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
          /:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlackProxyFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - SlackProxyFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SlackProxyFunction
      Principal: apigateway.amazonaws.com
Outputs:
  SlackProxyAppUrl:
    Description: App endpoint URL
    Value: !Sub "https://${SlackProxyAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"